name: 'Playground'
version: 1.0.0
main: fr.zuruh.playground.PlaygroundPlugin
api-version: 1.20
commands:
  vanish:
    description: vanish
    usage: /vanish
    permission: playground.command.vanish
